### ISSUE TITLE
[Important] main thread deadlock

### ISSUE THREAD

**Issue by luenlin** [superfluke/hexlands#16]
`https://paste.feed-the-beast.com/view/c74471da`

"Server thread" #29 prio=5 os_prio=0 tid=0x0000000039379800 nid=0x384c waiting for monitor entry [0x0000000036d9c000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.String.substring(Unknown Source)
	at sun.reflect.misc.ReflectUtil.isNonPublicProxyClass(Unknown Source)
	at java.lang.ClassLoader.checkPackageAccess(Unknown Source)
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:51)
	- locked <0x0000000649e6a368> (a net.minecraft.world.gen.structure.MapGenVillage)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:34)
	at fluke.hexlands.world.ChunkGeneratorOverworldHex.func_180514_a(ChunkGeneratorOverworldHex.java:648)
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.func_180514_a(SpongeChunkGenerator.java:527)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:102)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

   Locked ownable synchronizers:
	- None

**Comment by luenlin** [comment]
@superfluke  yes

**Comment by luenlin** [comment]
Memory overflow + deadlock on main thread

**Comment by superfluke** [comment]
Any other mods? Any logs from the crash/deadlock without sponge?

**Comment by luenlin** [comment]
Forge tries to run but memory overflow occurs when the player runs the graph

**Comment by luenlin** [comment]
Because it is a server, it may not be able to test so much
If you do not plan to repair sponge related errors please inform

**Comment by superfluke** [comment]
Is it sponge related? You said you're still having errors without sponge correct, any logs might help.

**Comment by luenlin** [comment]
Sorry for the memory overflow causing the command window to freeze directly.
So I can't provide any relevant reports.
Because it was not generated at all

**Comment by superfluke** [comment]
You should still have a a file named something like latest.log in your logs folder

**Comment by luenlin** [comment]
[https://paste.feed-the-beast.com/view/7dcfd47c](url)

**Comment by superfluke** [comment]
That log has sponge as well. I cannot manage to replicate this but feel free to reopen if you do have a log without sponge, otherwise try reporting this issue to them.
